"""Same-slot bundle detector.

Derived from Anon-Bundler ``jito.ts`` + ``pumpfun.ts``:
  - Jito bundles land atomically: all 5 TXs in the SAME slot
  - Structure: 1 create TX + up to 3 buy TXs + 1 Jito tip TX
  - Tip TX is a SOL transfer to a known Jito tip account
  - Buy TXs are from distinct wallets (generated by wallets.ts)

Detection strategy:
  Given a token mint, find the slot where ``InitializeMint`` / Pump.fun
  create occurred.  Then examine ALL transactions in that slot to detect
  coordinated buys from distinct wallets — especially ones that include
  a Jito tip transfer.

Signals produced:
  - create_slot:          slot of the token creation TX
  - same_slot_buys:       number of buy TXs in the same slot
  - same_slot_wallets:    distinct buyer addresses in same slot
  - jito_tip_detected:    whether a Jito tip TX was found in the bundle
  - jito_tip_lamports:    tip amount (bundler default: 950,000)
  - bundle_size:          total TXs detected in the bundle (create + buys + tip)
  - score:                0-100 sub-score
"""
from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from typing import Any

from loguru import logger

from src.analyzers.rpc import rpc


# Known Jito tip accounts (from Anon-Bundler utils.ts FALLBACK_TIP_ACCOUNTS)
JITO_TIP_ACCOUNTS = frozenset({
    "96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5",
    "HFqU5x63VTqvQss8hp11i4bPUZPon1DEaf6fk3K5NXNY",
    "Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY",
    "ADaUMid9yfUytqMBgopwjb2DTLSLm3CnLmSE9fUCPvo1",
    "DfXygSm4jCyNCybVYYK6DwvWqjKee8pbDmJGcLWNDXjh",
    "ADuUkR4vqLUMWXxW9gh6D6L8pMSawimctcNZ5pGwDcEt",
    "DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL",
    "3AVi9Tg9Uo68tJfuvoKvqKNWKkC5wPdSSdeBnizKZ6jT",
})

# Pump.fun program ID (from pumpfun.ts)
PUMP_FUN_PROGRAM = "6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P"

# Bundler Jito tip default range
BUNDLER_TIP_RANGE = (100_000, 10_000_000)  # 0.0001 – 10 SOL


@dataclass
class BundleResult:
    create_slot: int = 0
    create_sig: str = ""
    same_slot_buys: int = 0
    same_slot_wallets: list[str] = field(default_factory=list)
    jito_tip_detected: bool = False
    jito_tip_lamports: int = 0
    bundle_size: int = 0
    score: float = 0.0
    flags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "create_slot": self.create_slot,
            "same_slot_buys": self.same_slot_buys,
            "same_slot_wallets": self.same_slot_wallets,
            "jito_tip_detected": self.jito_tip_detected,
            "jito_tip_lamports": self.jito_tip_lamports,
            "bundle_size": self.bundle_size,
            "score": self.score,
            "flags": self.flags,
        }


async def analyze_same_slot_bundle(
    mint: str,
    deployer: str,
) -> BundleResult:
    """Detect Jito-bundled launch pattern for a token.

    Parameters
    ----------
    mint : str
        Token mint address.
    deployer : str
        Deployer / creator wallet address.
    """
    result = BundleResult()

    try:
        # Step 1: Find the creation TX (first TX involving the mint)
        mint_sigs = await rpc.get_signatures_for_address(mint, limit=20)
        if not mint_sigs:
            return result

        # The creation TX is the earliest (last in the list, since results
        # are newest-first)
        create_info = mint_sigs[-1]
        result.create_slot = create_info.get("slot", 0)
        result.create_sig = create_info.get("signature", "")

        if result.create_slot == 0:
            return result

        # Step 2: Find all TXs from the deployer in the same slot range
        # (same slot = atomic Jito bundle)
        deployer_sigs = await rpc.get_signatures_for_address(deployer, limit=50)

        same_slot_sigs = [
            s for s in deployer_sigs
            if s.get("slot") == result.create_slot
        ]

        # Also check mint_sigs for buys from OTHER wallets in the same slot
        same_slot_mint_sigs = [
            s for s in mint_sigs
            if s.get("slot") == result.create_slot
        ]

        # Combine unique signatures in the same slot involving this mint
        all_same_slot = {s["signature"] for s in same_slot_sigs}
        all_same_slot.update(s["signature"] for s in same_slot_mint_sigs)

        # Step 3: Parse each TX in the same slot
        sem = asyncio.Semaphore(5)
        buy_wallets: list[str] = []
        tip_detected = False
        tip_amount = 0

        async def parse_tx(sig: str) -> None:
            nonlocal tip_detected, tip_amount
            async with sem:
                try:
                    tx = await rpc.get_transaction(sig)
                    if not tx:
                        return

                    meta = tx.get("meta", {})
                    if meta.get("err"):
                        return

                    msg = tx.get("transaction", {}).get("message", {})
                    account_keys = msg.get("accountKeys", [])
                    keys_list = []
                    for ak in account_keys:
                        k = ak if isinstance(ak, str) else ak.get("pubkey", "")
                        keys_list.append(k)

                    instructions = msg.get("instructions", [])

                    # Check for Jito tip: SOL transfer to a known tip account
                    for ix in instructions:
                        program_id = ix.get("programId", "")
                        if program_id == "11111111111111111111111111111111":
                            parsed = ix.get("parsed", {})
                            if parsed.get("type") == "transfer":
                                dest = parsed.get("info", {}).get("destination", "")
                                lamports = parsed.get("info", {}).get("lamports", 0)
                                if dest in JITO_TIP_ACCOUNTS:
                                    tip_detected = True
                                    tip_amount = max(tip_amount, lamports)

                    # Check for Pump.fun buy (program invocation + not the create TX)
                    has_pump_ix = any(
                        ix.get("programId", "") == PUMP_FUN_PROGRAM
                        for ix in instructions
                    )

                    if has_pump_ix and sig != result.create_sig:
                        # The fee payer is the buyer
                        if keys_list:
                            signer = keys_list[0]
                            if signer != deployer and signer not in buy_wallets:
                                buy_wallets.append(signer)

                except Exception as e:
                    logger.debug(f"Bundle detector: failed to parse {sig[:16]}: {e}")

        await asyncio.gather(*(parse_tx(sig) for sig in all_same_slot))

        result.same_slot_buys = len(buy_wallets)
        result.same_slot_wallets = buy_wallets
        result.jito_tip_detected = tip_detected
        result.jito_tip_lamports = tip_amount
        result.bundle_size = 1 + len(buy_wallets) + (1 if tip_detected else 0)

        # Flags
        if result.same_slot_buys > 0:
            result.flags.append(
                f"{result.same_slot_buys} buy TXs from distinct wallets in same slot as create"
            )

        if tip_detected:
            tip_sol = round(tip_amount / 1e9, 6)
            result.flags.append(f"Jito tip detected: {tip_sol} SOL to tip account")

        if result.bundle_size >= 3:
            result.flags.append(
                f"Bundle structure: {result.bundle_size} TXs "
                f"(1 create + {result.same_slot_buys} buys"
                f"{' + 1 tip' if tip_detected else ''})"
            )

        # Exact Jito 5-TX pattern (1 create + 3 buys + 1 tip)
        if result.bundle_size == 5 and result.same_slot_buys == 3 and tip_detected:
            result.flags.append(
                "EXACT Jito bundle pattern: create + 3 buys + tip = 5 TXs"
            )

        # Score
        score = 0.0

        # Same-slot buys
        if result.same_slot_buys >= 3:
            score += 35
        elif result.same_slot_buys >= 2:
            score += 25
        elif result.same_slot_buys >= 1:
            score += 15

        # Jito tip presence
        if tip_detected:
            score += 25
            # Tip in bundler default range
            if BUNDLER_TIP_RANGE[0] <= tip_amount <= BUNDLER_TIP_RANGE[1]:
                score += 10

        # Exact 5-TX pattern
        if result.bundle_size == 5 and tip_detected:
            score += 20

        # Multiple distinct buyer wallets (sybil)
        if result.same_slot_buys >= 3:
            score += 10

        result.score = min(100.0, round(score, 1))
        return result

    except Exception as e:
        logger.error(f"Same-slot bundle analysis failed: {e}")
        return result
